export const routes = [
  {
    key: 'dashboard',
    label: '工作台',
    pages: [
      { key: 'dashboard-home', label: '首页总览', type: 'overview', desc: '平台状态、待办提醒、模块入口、关键指标汇总。' },
      { key: 'dashboard-todos', label: '待处理事项', type: 'worklist', desc: '汇总各模块待审批、待勾稽、待同步、待导入确认的数据。' },
      { key: 'dashboard-notices', label: '系统通知', type: 'notice', desc: '消息提醒、同步失败提醒、权限变更提醒。' },
    ],
  },
  {
    key: 'auth',
    label: '统一用户权限',
    pages: [
      { key: 'auth-home', label: '权限首页', type: 'overview', desc: '用户、组织、角色、权限、登录状态总览。' },
      { key: 'auth-login', label: '登录入口', type: 'entry', desc: '飞书登录、管理员本地登录、旧页面统一跳转入口。' },
      { key: 'auth-users', label: '用户管理', type: 'list', desc: '用户列表、搜索、详情、启停、角色分配、最近登录。' },
      { key: 'auth-departments', label: '部门管理', type: 'tree', desc: '部门树、成员归属、负责人、飞书同步与同步日志。' },
      { key: 'auth-roles', label: '角色管理', type: 'list', desc: '角色新建、复制、编辑、停用、绑定用户。' },
      { key: 'auth-permissions', label: '权限管理', type: 'config', desc: '菜单权限、操作权限、数据权限、字段权限配置。' },
      { key: 'auth-admins', label: '管理员账号', type: 'list', desc: '管理员账号创建、停用、重置密码、权限范围设置。' },
      { key: 'auth-logs', label: '审计日志', type: 'log', desc: '登录日志、权限变更日志、用户状态日志。' },
      { key: 'auth-legacy', label: '旧页面接入', type: 'gateway', desc: '旧系统入口管理、登录态透传、纳管进度。' },
    ],
  },
  {
    key: 'ledger',
    label: '新流水记账',
    pages: [
      { key: 'ledger-home', label: '记账首页', type: 'overview', desc: '总余额、收入支出趋势、账户汇总、待处理事项。' },
      { key: 'ledger-transactions', label: '流水明细', type: 'list', desc: '流水列表、筛选、批量操作、详情、编辑。' },
      { key: 'ledger-transaction-detail', label: '流水详情', type: 'detail', desc: '完整字段、附件、发票信息、报销状态、匹配记录。' },
      { key: 'ledger-create', label: '新增记账', type: 'form', desc: '收入、支出、转账、退款录入页面。' },
      { key: 'ledger-accounts', label: '账户管理', type: 'crud', desc: '账户增删改查、账户流水、账户类型与余额管理。' },
      { key: 'ledger-categories', label: '分类标签', type: 'crud', desc: '一级分类/二级分类管理、启停、排序、分类汇总金额。' },
      { key: 'ledger-members', label: '成员角色', type: 'assignment', desc: '谁可以记账、谁可查看本部门、谁可看全部账。' },
      { key: 'ledger-counterparties', label: '往来单位 / 供应商', type: 'master-data', desc: '供应商、商家、服务商等往来对象展示与引用。' },
      { key: 'ledger-project-tags', label: '项目分类', type: 'crud', desc: '项目标签、业务项目、费用归属分类维护。' },
      { key: 'ledger-reimbursements', label: '报销管理', type: 'workflow', desc: '待提交、审批中、已通过、已驳回、已完成记录。' },
      { key: 'ledger-imports', label: '导入批次', type: 'import', desc: '银行流水、空中云汇流水导入批次管理。' },
      { key: 'ledger-import-confirm', label: '导入确认', type: 'confirm', desc: '参考随手记“记多笔”的批量确认与补录页面。' },
      { key: 'ledger-import-matches', label: '匹配结果', type: 'match', desc: '系统匹配候选、未匹配原因、人工处理记录。' },
      { key: 'ledger-reports', label: '收支报表', type: 'report', desc: '收支汇总、账户报表、分类汇总、成员维度统计。' },
      { key: 'ledger-migration', label: '随手记迁移', type: 'migration', desc: '历史账户、流水、分类、商家数据迁移状态。' },
    ],
  },
  {
    key: 'reconciliation',
    label: '勾稽系统',
    pages: [
      { key: 'recon-home', label: '数据总览', type: 'overview', desc: '采购、请款、发货、发票、勾稽状态与提醒总览。' },
      { key: 'recon-purchase-list', label: '采购单列表', type: 'list', desc: '采购单筛选、状态查看、详情入口。' },
      { key: 'recon-purchase-detail', label: '采购单详情', type: 'detail', desc: '采购单基础信息与发票/请款/发货双向关系。' },
      { key: 'recon-payment-list', label: '请款单列表', type: 'list', desc: '请款单状态、未取票提醒、不提醒标记。' },
      { key: 'recon-payment-detail', label: '请款单详情', type: 'detail', desc: '请款单与发票/采购/发货双向追溯。' },
      { key: 'recon-delivery-list', label: '发货单列表', type: 'list', desc: '发货单是第一阶段关键勾稽对象。' },
      { key: 'recon-delivery-detail', label: '发货单详情', type: 'detail', desc: '发票覆盖情况、采购与请款链路追溯。' },
      { key: 'recon-invoice-list', label: '发票列表', type: 'list', desc: '发票筛选、金额、日期、匹配状态查看。' },
      { key: 'recon-invoice-detail', label: '发票详情', type: 'detail', desc: '反查采购单、请款单、发货单及对应金额。' },
      { key: 'recon-relations', label: '关系维护', type: 'crud', desc: '系统推荐 + 人工确认，维护金额拆分与备注。' },
      { key: 'recon-trace', label: '双向追溯', type: 'trace', desc: '从任一对象出发查看完整勾稽链路。' },
      { key: 'recon-reminders', label: '提醒清单', type: 'reminder', desc: '未开票、未取票、覆盖不足、不提醒原因记录。' },
      { key: 'recon-reports', label: '财务报表', type: 'report', desc: '供应商开票汇总、金额对比、明细报表。' },
    ],
  },
  {
    key: 'product-dev',
    label: '新品开发',
    pages: [
      { key: 'product-home', label: '新品首页', type: 'overview', desc: '项目总量、阶段分布、待审批、待同步总览。' },
      { key: 'product-board', label: '进度看板', type: 'board', desc: '按待调研、打样、待报价、待审批、待上线等状态看板展示。' },
      { key: 'product-list', label: '项目列表', type: 'list', desc: '项目筛选、搜索、负责人、平台、状态查看。' },
      { key: 'product-detail', label: '项目详情', type: 'detail', desc: '主档、图片、调研文件、打样、报价、利润试算、审批与同步记录。' },
      { key: 'product-create', label: '新建 / 编辑项目', type: 'form', desc: '新品项目主档录入与维护。' },
      { key: 'product-sampling', label: '打样管理', type: 'crud', desc: '多轮打样记录、评审结果、改进意见。' },
      { key: 'product-quotes', label: '报价管理', type: 'crud', desc: '多供应商报价对比、首选供应商、税率、MOQ、交期。' },
      { key: 'product-profit', label: '利润试算', type: 'calculator', desc: '亚马逊口径利润测算、方案对比、历史记录。' },
      { key: 'product-approval', label: '审批中心', type: 'workflow', desc: '立项审批、定版审批、上线审批节点与记录。' },
      { key: 'product-sync', label: '领星同步', type: 'sync', desc: '人工同步、失败原因、返回结果、重试记录。' },
      { key: 'product-spu', label: 'SPU / SKU 归属', type: 'structure', desc: '独立 SKU、新建 SPU、归入已有 SPU 的归属关系。' },
      { key: 'product-dicts', label: '基础分类', type: 'crud', desc: '产品分类、品牌、材质、标签、负责人组等字典维护。' },
    ],
  },
];
