export const mockProjects = [
  {
    id: 1,
    projectCode: 'NP-20260418-001',
    productName: '车载磁吸手机支架',
    sku: 'SKU-MAG-001',
    developerName: '张琳',
    ownerName: '王凯',
    targetPlatform: 'Amazon',
    targetMarket: 'US',
    estimatedCost: 18.6,
    targetPrice: 19.99,
    grossMarginTarget: 0.32,
    projectStatus: '待立项审批',
  },
  {
    id: 2,
    projectCode: 'NP-20260418-002',
    productName: '便携式桌面收纳盒',
    sku: 'SKU-BOX-001',
    developerName: '陈悦',
    ownerName: '李森',
    targetPlatform: 'Amazon',
    targetMarket: 'DE',
    estimatedCost: 12.4,
    targetPrice: 24.99,
    grossMarginTarget: 0.35,
    projectStatus: '已同步领星',
  },
];

export const mockQuotes = [
  {
    id: 1,
    projectId: 1,
    supplierName: '深圳创优五金',
    supplierErpId: 'SUP-001',
    currency: 'CNY',
    quotePrice: 16.8,
    moq: 500,
    taxIncluded: 1,
    deliveryDays: 18,
    preferred: 1,
  },
  {
    id: 2,
    projectId: 1,
    supplierName: '东莞精工塑胶',
    supplierErpId: 'SUP-002',
    currency: 'CNY',
    quotePrice: 17.5,
    moq: 300,
    taxIncluded: 1,
    deliveryDays: 15,
    preferred: 0,
  },
  {
    id: 3,
    projectId: 2,
    supplierName: '宁波优造家居',
    supplierErpId: 'SUP-003',
    currency: 'CNY',
    quotePrice: 11.2,
    moq: 800,
    taxIncluded: 1,
    deliveryDays: 20,
    preferred: 1,
  },
];

export const mockProfitCalculations = [
  {
    id: 1,
    projectId: 1,
    salesPriceUsd: 19.99,
    exchangeRate: 7.2,
    productCostRmb: 16.8,
    accessoryCostRmb: 1.8,
    shippingExpress: 24,
    shippingAir: 10,
    shippingSea: 4,
    selectedPlan: 'air',
    selectedProfit: 37.13,
    selectedProfitRate: 0.258,
    calculatedBy: '张琳',
  },
  {
    id: 2,
    projectId: 2,
    salesPriceUsd: 24.99,
    exchangeRate: 7.2,
    productCostRmb: 11.2,
    accessoryCostRmb: 1.4,
    shippingExpress: 18,
    shippingAir: 8,
    shippingSea: 3.5,
    selectedPlan: 'sea',
    selectedProfit: 72.33,
    selectedProfitRate: 0.402,
    calculatedBy: '陈悦',
  },
];

export const mockSampleRecords = [
  {
    id: 1,
    projectId: 1,
    roundNo: 1,
    supplierName: '深圳创优五金',
    sampleFee: 300,
    reviewResult: 'pass',
    improvementNotes: '磁吸强度通过',
  },
  {
    id: 2,
    projectId: 2,
    roundNo: 2,
    supplierName: '宁波优造家居',
    sampleFee: 260,
    reviewResult: 'pass',
    improvementNotes: '材质确认通过',
  },
];

export const mockSyncRecords = [
  {
    id: 1,
    projectId: 2,
    syncStatus: 'success',
    syncedBy: '李森',
    syncTime: '2026-04-18 10:30:00',
    resultMessage: 'lingxing sync success',
  },
  {
    id: 2,
    projectId: 1,
    syncStatus: 'pending',
    syncedBy: '',
    syncTime: '',
    resultMessage: 'waiting for approval',
  },
];
